### ISSUE TITLE
[CI] Add testing and make script to keep the consistency of env and dependencies

### ISSUE THREAD

**Issue by YuCJ** [twreporter/twreporter-npm-packages#3]
## TODO

- [x] Add testing to pre-commit and pre-publish hooks to prevent inconsistency in some major dependencies like `react`, `react-router`, `styled-components`. So that the consumer (like `twreporter-react`) will not install duplicate module.

- [x] Add make scripts to create the `makefile` of each package from a root source file.

- [x] Add testing to confirm there is no difference among the package's `makefile`s.

- [ ] Add make scripts to add git tag with package name and version automatically. See [reference](https://coderwall.com/p/dr4uvw/easy-version-publishing-to-npm-via-makefile)

**Comment by taylrj** [comment]
Closing since current CI can add git tag, version, publish automatically by utilizing [lerna ](https://github.com/lerna/lerna).
